import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Plus, LayoutGrid, List, Columns3, MoreHorizontal, Play, Star, X, Film, Tv, Sparkles } from 'lucide-react';
import './styles.css';

type Status = 'watching' | 'watched' | 'next'; type Kind = 'Movie' | 'Series' | 'Anime';
type Entry = { id:number; title:string; kind:Kind; status:Status; rating:number; year:number; platform:string; poster:string; progress?:string; description:string };
const demo:Entry[]=[
{id:1,title:'The Last of Us',kind:'Series',status:'watching',rating:9.2,year:2023,platform:'HBO Max',poster:'https://image.tmdb.org/t/p/w780/uQUq6g8d9y8f3r6q4w1m2d0c.jpg',progress:'S1:E4',description:'A journey across a post-pandemic America.'},
{id:2,title:'Dune: Part Two',kind:'Movie',status:'watched',rating:9.0,year:2024,platform:'Max',poster:'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',description:'Long live the fighters.'},
{id:3,title:'Frieren: Beyond Journey’s End',kind:'Anime',status:'next',rating:8.8,year:2023,platform:'Crunchyroll',poster:'https://image.tmdb.org/t/p/w780/edZc1j7cC8H9m2Y6z0P8.jpg',description:'The end of an adventure is only the beginning.'},
{id:4,title:'Severance',kind:'Series',status:'next',rating:8.7,year:2022,platform:'Apple TV+',poster:'https://image.tmdb.org/t/p/w780/l0qVZIpXtIo7km9u5Yqh0n.jpg',description:'What if your work and home memories were separated?'}];
const labels={watching:'ดูอยู่',watched:'ดูแล้ว',next:'ดูต่อ'};
function App(){const [entries,setEntries]=useState<Entry[]>(()=>JSON.parse(localStorage.getItem('watch-demo')||JSON.stringify(demo))); const [query,setQuery]=useState(''); const [filter,setFilter]=useState<'all'|Status>('all'); const [view,setView]=useState<'grid'|'list'|'columns'>('grid'); const [modal,setModal]=useState(false); const [draft,setDraft]=useState({title:'',kind:'Movie' as Kind,status:'next' as Status,platform:'',rating:8,year:2025,poster:'',description:''}); useEffect(()=>localStorage.setItem('watch-demo',JSON.stringify(entries)),[entries]);
const filtered=useMemo(()=>entries.filter(e=>(filter==='all'||e.status===filter)&&e.title.toLowerCase().includes(query.toLowerCase())),[entries,filter,query]);
function add(){if(!draft.title.trim())return;setEntries([{...draft,id:Date.now()},...entries]);setModal(false);setDraft({...draft,title:'',description:'',poster:''})} function remove(id:number){setEntries(entries.filter(e=>e.id!==id))}
return <div className="app"><aside><div className="brand"><span>◒</span><b>watchlog</b></div><nav><button className="active"><LayoutGrid size={18}/> Library</button><button><Star size={18}/> Favorites</button></nav><div className="side-bottom"><small>YOUR LIBRARY</small><p>All titles <b>{entries.length}</b></p><p>Currently watching <b>{entries.filter(e=>e.status==='watching').length}</b></p><p>Completed <b>{entries.filter(e=>e.status==='watched').length}</b></p></div><div className="profile"><div className="avatar">J</div><span>Jornjud<br/><small>Personal space</small></span><MoreHorizontal size={18}/></div></aside><main><header><div><p className="eyebrow">MY LIBRARY / 2025</p><h1>ดูแล้ว ดูอยู่ ดูต่อ</h1><p className="subtitle">Keep track of what you watch, what you love, and what’s next.</p></div><button className="add" onClick={()=>setModal(true)}><Plus size={18}/> Add title</button></header><section className="toolbar"><div className="search"><Search size={18}/><input placeholder="Search your library..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filters">{(['all','watching','watched','next'] as const).map(f=><button className={filter===f?'selected':''} onClick={()=>setFilter(f)} key={f}>{f==='all'?'All titles':labels[f]}</button>)}</div><div className="views">{([[ 'grid',LayoutGrid],['list',List],['columns',Columns3]] as const).map(([v,I])=><button className={view===v?'selected':''} onClick={()=>setView(v)} key={v}><I size={17}/></button>)}</div></section>{view==='columns'?<div className="columns">{(['watching','next','watched'] as Status[]).map(s=><section className="column" key={s}><h2>{labels[s]} <span>{filtered.filter(e=>e.status===s).length}</span></h2>{filtered.filter(e=>e.status===s).map(e=><Card e={e} list onDelete={remove}/>)}</section>)}</div>:<div className={view==='list'?'cards list':'cards'}>{filtered.map(e=><Card e={e} onDelete={remove}/>)}</div>}{!filtered.length&&<div className="empty"><Sparkles size={30}/><h2>No titles found</h2><p>Try another search or add something new to your library.</p></div>}</main>{modal&&<div className="overlay"><div className="modal"><button className="close" onClick={()=>setModal(false)}><X/></button><p className="eyebrow">NEW ENTRY</p><h2>Add a title</h2>{(['title','platform','poster','description'] as const).map(k=><input key={k} placeholder={k==='title'?'Title *':k[0].toUpperCase()+k.slice(1)} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/>)}<div className="row"><select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as Kind})}><option>Movie</option><option>Series</option><option>Anime</option></select><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Status})}><option value="next">ดูต่อ</option><option value="watching">ดูอยู่</option><option value="watched">ดูแล้ว</option></select></div><button className="add full" onClick={add}>Save to library</button></div></div>}</div>}
function Card({e,onDelete,list=false}:{e:Entry;onDelete:(id:number)=>void;list?:boolean}){return <article className={'card '+(list?'compact':'')}><div className="poster" style={{backgroundImage:`url(${e.poster})`}}><span>{e.kind}</span></div><div className="card-body"><div className="card-top"><span className={'status '+e.status}>{labels[e.status]}</span><button onClick={()=>onDelete(e.id)} aria-label="Delete"><MoreHorizontal size={18}/></button></div><h3>{e.title}</h3><p className="meta">{e.year} · {e.platform} {e.progress&&' · '+e.progress}</p><p className="desc">{e.description}</p><div className="rating"><Star size={15} fill="currentColor"/> {e.rating.toFixed(1)} <span>/ 10</span></div></div></article>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
