import type {VercelRequest,VercelResponse} from '@vercel/node';
import {google} from 'googleapis';
import {oauth,json,method,session} from './_lib/auth';
const headers=['id','title','kind','status','rating','year','platform','poster','progress','description','updatedAt'];
async function api(req:VercelRequest){const s=session(req);if(!s)throw Object.assign(new Error('unauthorized'),{status:401});const a=oauth();a.setCredentials({refresh_token:s.refreshToken});return {sheets:google.sheets({version:'v4',auth:a}),drive:google.drive({version:'v3',auth:a})}}
export default async function handler(req:VercelRequest,res:VercelResponse){try{const {sheets,drive}=await api(req);let id=process.env.GOOGLE_SHEET_ID; if(!id){const f=await drive.files.create({requestBody:{name:'watchlog library',mimeType:'application/vnd.google-apps.spreadsheet'},fields:'id'});id=f.data.id!;await sheets.spreadsheets.values.update({spreadsheetId:id,range:'Sheet1!A1:K1',valueInputOption:'RAW',requestBody:{values:[headers]}})}
 if(req.method==='GET'){const r=await sheets.spreadsheets.values.get({spreadsheetId:id,range:'Sheet1!A2:K'});const entries=(r.data.values||[]).filter(x=>x[0]).map(x=>Object.fromEntries(headers.map((h,i)=>[h,x[i]||''])));return json(res,200,{entries,sheetId:id})}
 if(req.method==='POST'){const e={...req.body,id:String(Date.now()),updatedAt:new Date().toISOString()};await sheets.spreadsheets.values.append({spreadsheetId:id,range:'Sheet1!A:K',valueInputOption:'RAW',requestBody:{values:[headers.map(h=>e[h]??'')]}});return json(res,201,{entry:e})}
 if(req.method==='DELETE'){const idv=String(req.query.id||'');const r=await sheets.spreadsheets.values.get({spreadsheetId:id,range:'Sheet1!A2:K'});const row=(r.data.values||[]).findIndex(x=>x[0]===idv);if(row<0)return json(res,404,{error:'not_found'});const meta=await sheets.spreadsheets.get({spreadsheetId:id,fields:'sheets.properties'});const sheetId=meta.data.sheets?.[0].properties?.sheetId||0;await sheets.spreadsheets.batchUpdate({spreadsheetId:id,requestBody:{requests:[{deleteDimension:{range:{sheetId,dimension:'ROWS',startIndex:row+1,endIndex:row+2}}}]}});return json(res,200,{ok:true})}
 return json(res,405,{error:'method_not_allowed'})}catch(e:any){return json(res,e.status||500,{error:e.message||'sheets_failed'})}}
